Document: bolt
Title: Debian bolt Manual
Author: <insert document author here>
Abstract: This manual describes what bolt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bolt/bolt.sgml.gz

Format: postscript
Files: /usr/share/doc/bolt/bolt.ps.gz

Format: text
Files: /usr/share/doc/bolt/bolt.text.gz

Format: HTML
Index: /usr/share/doc/bolt/html/index.html
Files: /usr/share/doc/bolt/html/*.html
